import type {
  ActivityItem,
  AdminClient,
  AdminContract,
  AdminDocument,
  AdminInquiry,
  AdminNotification,
  AdminPayment,
  AdminPublication,
  AdminRental,
  AdminSale,
  AdminUser,
  AdminVisit,
  AuditEvent,
  CompanySettings,
  PropertyMeta,
} from '../types'

const daysAgo = (n: number) => {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

const daysFromNow = (n: number) => {
  const d = new Date()
  d.setDate(d.getDate() + n)
  return d.toISOString()
}

export const seedClients: AdminClient[] = [
  {
    id: 'C-521',
    firstName: 'Juan',
    lastName: 'Pérez',
    dni: '32.456.789',
    phone: '+54 9 351 555-0101',
    email: 'juan.perez@email.com',
    address: 'Av. Colón 1234, Córdoba',
    birthDate: '1988-04-12',
    type: 'comprador',
    seeking: ['Departamento', 'Casa'],
    operation: 'comprar',
    budgetMin: 50_000_000,
    budgetMax: 100_000_000,
    locations: ['Nueva Córdoba', 'Centro', 'General Paz'],
    firstContact: daysAgo(25),
    lastContact: daysAgo(1),
    nextContact: daysFromNow(2),
    agentId: 'U-3',
    status: 'negociando',
    notes: 'Interesado en dpto. Nueva Córdoba. Oferta en curso.',
    createdAt: daysAgo(25),
  },
  {
    id: 'C-522',
    firstName: 'María',
    lastName: 'Gómez',
    dni: '28.111.222',
    phone: '+54 9 351 555-0202',
    email: 'maria.gomez@email.com',
    address: 'Bv. San Juan 500',
    birthDate: '1992-09-03',
    type: 'inquilino',
    seeking: ['Departamento'],
    operation: 'alquilar',
    budgetMin: 350_000,
    budgetMax: 550_000,
    locations: ['Nueva Córdoba', 'Centro'],
    firstContact: daysAgo(8),
    lastContact: daysAgo(0),
    nextContact: daysFromNow(1),
    agentId: 'U-3',
    status: 'interesado',
    notes: 'Consultó disponibilidad por WhatsApp.',
    createdAt: daysAgo(8),
  },
  {
    id: 'C-523',
    firstName: 'Laura',
    lastName: 'Martínez',
    dni: '30.333.444',
    phone: '+54 9 351 555-0303',
    email: 'laura.m@email.com',
    address: 'General Paz 800',
    birthDate: '1985-01-20',
    type: 'propietario',
    seeking: [],
    operation: 'ambos',
    budgetMin: 0,
    budgetMax: 0,
    locations: ['General Paz'],
    firstContact: daysAgo(60),
    lastContact: daysAgo(10),
    nextContact: daysFromNow(7),
    agentId: 'U-1',
    status: 'cerrado',
    notes: 'Propietaria de Casa 3 ambientes.',
    createdAt: daysAgo(60),
  },
  {
    id: 'C-524',
    firstName: 'Carlos',
    lastName: 'Ruiz',
    dni: '25.777.888',
    phone: '+54 9 351 555-0404',
    email: 'carlos.ruiz@email.com',
    address: 'Cerro de las Rosas',
    birthDate: '1979-11-11',
    type: 'inversor',
    seeking: ['Local', 'Departamento'],
    operation: 'comprar',
    budgetMin: 80_000_000,
    budgetMax: 200_000_000,
    locations: ['Centro', 'Nueva Córdoba'],
    firstContact: daysAgo(15),
    lastContact: daysAgo(4),
    nextContact: daysFromNow(3),
    agentId: 'U-3',
    status: 'visitando',
    notes: 'Busca rentabilidad > 5%.',
    createdAt: daysAgo(15),
  },
  {
    id: 'C-525',
    firstName: 'Sofía',
    lastName: 'Fernández',
    dni: '35.999.000',
    phone: '+54 9 351 555-0505',
    email: 'sofia.f@email.com',
    address: 'Alberdi 200',
    birthDate: '1995-06-18',
    type: 'comprador',
    seeking: ['PH', 'Casa'],
    operation: 'comprar',
    budgetMin: 70_000_000,
    budgetMax: 120_000_000,
    locations: ['Alberdi', 'General Paz'],
    firstContact: daysAgo(3),
    lastContact: daysAgo(3),
    nextContact: daysFromNow(5),
    agentId: 'U-3',
    status: 'nuevo',
    notes: 'Primera consulta desde el sitio web.',
    createdAt: daysAgo(3),
  },
]

export const seedVisits: AdminVisit[] = [
  {
    id: 'V-101',
    propertyId: 'seed-1',
    propertyTitle: 'Dpto. 2 Amb. Recoleta',
    propertyLocation: 'Recoleta / Nueva Córdoba',
    clientId: 'C-521',
    clientName: 'Juan Pérez',
    agentId: 'U-3',
    agentName: 'Carlos Gómez',
    datetime: daysFromNow(1).replace(/T.*/, 'T10:30:00.000Z'),
    status: 'programada',
    notes: 'Llevar planos y comparables.',
    confirmed: false,
  },
  {
    id: 'V-102',
    propertyId: 'seed-3',
    propertyTitle: 'Casa Barrio Cerrado Belgrano',
    propertyLocation: 'General Paz',
    clientId: 'C-524',
    clientName: 'Carlos Ruiz',
    agentId: 'U-3',
    agentName: 'Carlos Gómez',
    datetime: daysFromNow(2).replace(/T.*/, 'T17:00:00.000Z'),
    status: 'confirmada',
    notes: '',
    confirmed: true,
  },
  {
    id: 'V-103',
    propertyId: 'seed-2',
    propertyTitle: 'Loft Moderno Palermo',
    propertyLocation: 'Palermo',
    clientId: 'C-522',
    clientName: 'María Gómez',
    agentId: 'U-3',
    agentName: 'Carlos Gómez',
    datetime: daysAgo(2).replace(/T.*/, 'T11:00:00.000Z'),
    status: 'realizada',
    notes: 'Le gustó la luminosidad. Pedir disponibilidad.',
    confirmed: true,
  },
  {
    id: 'V-104',
    propertyId: 'seed-4',
    propertyTitle: 'PH con Patio Palermo Hollywood',
    propertyLocation: 'Palermo Hollywood',
    clientId: 'C-525',
    clientName: 'Sofía Fernández',
    agentId: 'U-1',
    agentName: 'Andrés García',
    datetime: daysFromNow(0).replace(/T.*/, 'T16:00:00.000Z'),
    status: 'programada',
    notes: '',
    confirmed: true,
  },
]

export const seedSales: AdminSale[] = [
  {
    id: 'S-201',
    propertyId: 'seed-1',
    propertyTitle: 'Dpto. 2 Amb. Recoleta',
    buyerId: 'C-521',
    buyerName: 'Juan Pérez',
    sellerName: 'Inmobiliaria MobiHouse',
    agentId: 'U-3',
    agentName: 'Carlos Gómez',
    price: 85_000_000,
    commission: 2_550_000,
    deposit: 5_000_000,
    balance: 80_000_000,
    paymentMethod: 'Transferencia + hipoteca',
    date: daysAgo(1),
    stage: 'reserva',
    status: 'reserva',
  },
  {
    id: 'S-202',
    propertyId: 'seed-3',
    propertyTitle: 'Casa Barrio Cerrado Belgrano',
    buyerId: 'C-524',
    buyerName: 'Carlos Ruiz',
    sellerName: 'Laura Martínez',
    agentId: 'U-3',
    agentName: 'Carlos Gómez',
    price: 120_000_000,
    commission: 3_600_000,
    deposit: 10_000_000,
    balance: 110_000_000,
    paymentMethod: 'Contado',
    date: daysAgo(5),
    stage: 'negociacion',
    status: 'en_negociacion',
  },
  {
    id: 'S-203',
    propertyId: 'seed-4',
    propertyTitle: 'PH con Patio Palermo Hollywood',
    buyerId: 'C-525',
    buyerName: 'Sofía Fernández',
    sellerName: 'Particular',
    agentId: 'U-1',
    agentName: 'Andrés García',
    price: 95_000_000,
    commission: 2_850_000,
    deposit: 0,
    balance: 95_000_000,
    paymentMethod: 'A definir',
    date: daysAgo(3),
    stage: 'visita',
    status: 'en_negociacion',
  },
  {
    id: 'S-204',
    propertyId: 'seed-1',
    propertyTitle: 'Dpto. histórico cerrado',
    buyerId: 'C-523',
    buyerName: 'Laura Martínez',
    sellerName: 'Particular',
    agentId: 'U-1',
    agentName: 'Andrés García',
    price: 72_000_000,
    commission: 2_160_000,
    deposit: 72_000_000,
    balance: 0,
    paymentMethod: 'Contado',
    date: daysAgo(40),
    stage: 'venta',
    status: 'cerrada',
  },
]

export const seedRentals: AdminRental[] = [
  {
    id: 'R-301',
    propertyId: 'seed-2',
    propertyTitle: 'Loft Moderno Palermo',
    tenantId: 'C-522',
    tenantName: 'María Gómez',
    ownerName: 'Andrés García',
    monthlyPrice: 450_000,
    deposit: 900_000,
    startDate: daysAgo(90),
    endDate: daysFromNow(25),
    adjustment: 'Semestral',
    adjustmentIndex: 'ICL',
    status: 'proximo_vencer',
  },
  {
    id: 'R-302',
    propertyId: 'seed-4',
    propertyTitle: 'PH Alquiler temporal',
    tenantId: 'C-524',
    tenantName: 'Carlos Ruiz',
    ownerName: 'Laura Martínez',
    monthlyPrice: 380_000,
    deposit: 760_000,
    startDate: daysAgo(200),
    endDate: daysFromNow(160),
    adjustment: 'Anual',
    adjustmentIndex: 'IPC',
    status: 'activo',
  },
]

export const seedContracts: AdminContract[] = [
  {
    id: 'CT-1042',
    number: 'CT-1042',
    type: 'reserva',
    propertyId: 'seed-1',
    propertyTitle: 'Dpto. 2 Amb. Recoleta',
    clientId: 'C-521',
    clientName: 'Juan Pérez',
    startDate: daysAgo(1),
    endDate: daysFromNow(30),
    status: 'activo',
    amount: 5_000_000,
  },
  {
    id: 'CT-1043',
    number: 'CT-1043',
    type: 'alquiler',
    propertyId: 'seed-2',
    propertyTitle: 'Loft Moderno Palermo',
    clientId: 'C-522',
    clientName: 'María Gómez',
    startDate: daysAgo(90),
    endDate: daysFromNow(25),
    status: 'activo',
    amount: 450_000,
  },
  {
    id: 'CT-1040',
    number: 'CT-1040',
    type: 'compraventa',
    propertyId: 'seed-1',
    propertyTitle: 'Dpto. histórico cerrado',
    clientId: 'C-523',
    clientName: 'Laura Martínez',
    startDate: daysAgo(40),
    endDate: daysAgo(40),
    status: 'activo',
    amount: 72_000_000,
  },
  {
    id: 'CT-1044',
    number: 'CT-1044',
    type: 'compraventa',
    propertyId: 'seed-3',
    propertyTitle: 'Casa Belgrano',
    clientId: 'C-524',
    clientName: 'Carlos Ruiz',
    startDate: daysAgo(2),
    endDate: daysFromNow(45),
    status: 'pendiente_firma',
    amount: 120_000_000,
  },
]

export const seedPayments: AdminPayment[] = [
  {
    id: 'PAY-1',
    clientId: 'C-521',
    clientName: 'Juan Pérez',
    propertyId: 'seed-1',
    propertyTitle: 'Dpto. 2 Amb. Recoleta',
    concept: 'Seña / Reserva',
    amount: 5_000_000,
    date: daysAgo(1),
    method: 'Transferencia',
    status: 'pagado',
  },
  {
    id: 'PAY-2',
    clientId: 'C-522',
    clientName: 'María Gómez',
    propertyId: 'seed-2',
    propertyTitle: 'Loft Moderno Palermo',
    concept: 'Alquiler septiembre',
    amount: 450_000,
    date: daysAgo(5),
    method: 'Débito automático',
    status: 'pagado',
  },
  {
    id: 'PAY-3',
    clientId: 'C-522',
    clientName: 'María Gómez',
    propertyId: 'seed-2',
    propertyTitle: 'Loft Moderno Palermo',
    concept: 'Alquiler octubre',
    amount: 450_000,
    date: daysFromNow(5),
    method: 'Débito automático',
    status: 'pendiente',
  },
  {
    id: 'PAY-4',
    clientId: 'C-524',
    clientName: 'Carlos Ruiz',
    propertyId: 'seed-3',
    propertyTitle: 'Casa Belgrano',
    concept: 'Seña negociación',
    amount: 10_000_000,
    date: daysAgo(4),
    method: 'Transferencia',
    status: 'parcial',
  },
  {
    id: 'PAY-5',
    clientId: 'C-523',
    clientName: 'Laura Martínez',
    propertyId: 'seed-4',
    propertyTitle: 'PH Alquiler',
    concept: 'Alquiler agosto',
    amount: 380_000,
    date: daysAgo(20),
    method: 'Efectivo',
    status: 'vencido',
  },
]

export const seedInquiries: AdminInquiry[] = [
  {
    id: 'INQ-1',
    clientId: 'C-522',
    clientName: 'María Gómez',
    propertyId: 'seed-2',
    propertyTitle: 'Loft Moderno Palermo',
    message: 'Hola, quisiera saber si el departamento sigue disponible.',
    agentId: 'U-3',
    agentName: 'Carlos Gómez',
    status: 'nueva',
    createdAt: daysAgo(0),
    unread: true,
  },
  {
    id: 'INQ-2',
    clientId: 'C-521',
    clientName: 'Juan Pérez',
    propertyId: 'seed-1',
    propertyTitle: 'Dpto. 2 Amb. Recoleta',
    message: '¿Se puede agendar una visita para mañana a las 10:30?',
    agentId: 'U-3',
    agentName: 'Carlos Gómez',
    status: 'en_conversacion',
    createdAt: daysAgo(1),
    unread: false,
  },
  {
    id: 'INQ-3',
    clientId: 'C-525',
    clientName: 'Sofía Fernández',
    propertyId: 'seed-4',
    propertyTitle: 'PH con Patio Palermo Hollywood',
    message: 'Me interesa el PH. ¿Aceptan permuta parcial?',
    agentId: 'U-1',
    agentName: 'Andrés García',
    status: 'pendiente',
    createdAt: daysAgo(3),
    unread: true,
  },
  {
    id: 'INQ-4',
    clientId: null,
    clientName: 'Visitante web',
    propertyId: 'seed-3',
    propertyTitle: 'Casa Barrio Cerrado Belgrano',
    message: 'Quiero saber expensas e impuestos aproximados.',
    agentId: 'U-1',
    agentName: 'Andrés García',
    status: 'respondida',
    createdAt: daysAgo(6),
    unread: false,
  },
]

export const seedPublications: AdminPublication[] = [
  {
    id: 'PUB-1',
    propertyId: 'seed-1',
    propertyTitle: 'Dpto. 2 Amb. Recoleta',
    channel: 'web',
    status: 'publicada',
    views: 1254,
    favorites: 84,
    inquiries: 27,
    url: '/propiedades/seed-1',
    updatedAt: daysAgo(1),
  },
  {
    id: 'PUB-2',
    propertyId: 'seed-2',
    propertyTitle: 'Loft Moderno Palermo',
    channel: 'instagram',
    status: 'publicada',
    views: 890,
    favorites: 61,
    inquiries: 18,
    url: 'https://instagram.com/p/demo',
    updatedAt: daysAgo(2),
  },
  {
    id: 'PUB-3',
    propertyId: 'seed-3',
    propertyTitle: 'Casa Barrio Cerrado Belgrano',
    channel: 'portales',
    status: 'publicada',
    views: 2100,
    favorites: 120,
    inquiries: 41,
    url: 'https://portales.demo/casa-belgrano',
    updatedAt: daysAgo(4),
  },
  {
    id: 'PUB-4',
    propertyId: 'seed-4',
    propertyTitle: 'PH con Patio Palermo Hollywood',
    channel: 'whatsapp',
    status: 'pausada',
    views: 340,
    favorites: 22,
    inquiries: 9,
    url: '',
    updatedAt: daysAgo(7),
  },
  {
    id: 'PUB-5',
    propertyId: 'seed-1',
    propertyTitle: 'Dpto. 2 Amb. Recoleta',
    channel: 'facebook',
    status: 'publicada',
    views: 670,
    favorites: 40,
    inquiries: 12,
    url: 'https://facebook.com/demo',
    updatedAt: daysAgo(3),
  },
]

export const seedDocuments: AdminDocument[] = [
  {
    id: 'DOC-1',
    name: 'Contrato alquiler — María Gómez',
    category: 'contratos',
    relatedType: 'client',
    relatedId: 'C-522',
    relatedLabel: 'María Gómez',
    type: 'PDF',
    size: '420 KB',
    uploadedAt: daysAgo(90),
  },
  {
    id: 'DOC-2',
    name: 'Reserva CT-1042 — Juan Pérez',
    category: 'contratos',
    relatedType: 'contract',
    relatedId: 'CT-1042',
    relatedLabel: 'CT-1042',
    type: 'PDF',
    size: '310 KB',
    uploadedAt: daysAgo(1),
  },
  {
    id: 'DOC-3',
    name: 'Plano Dpto Recoleta',
    category: 'planos',
    relatedType: 'property',
    relatedId: 'seed-1',
    relatedLabel: 'Dpto. Recoleta',
    type: 'PDF',
    size: '1.2 MB',
    uploadedAt: daysAgo(20),
  },
  {
    id: 'DOC-4',
    name: 'DNI Juan Pérez',
    category: 'clientes',
    relatedType: 'client',
    relatedId: 'C-521',
    relatedLabel: 'Juan Pérez',
    type: 'PDF',
    size: '180 KB',
    uploadedAt: daysAgo(10),
  },
  {
    id: 'DOC-5',
    name: 'Comprobante seña S-201',
    category: 'comprobantes',
    relatedType: 'general',
    relatedId: 'PAY-1',
    relatedLabel: 'Pago seña',
    type: 'PDF',
    size: '95 KB',
    uploadedAt: daysAgo(1),
  },
]

export const seedUsers: AdminUser[] = [
  {
    id: 'U-1',
    name: 'Andrés García',
    email: 'andres@mobihouse.com',
    role: 'super_admin',
    status: 'active',
    permissions: [...[
      'ver_propiedades',
      'crear_propiedades',
      'editar_propiedades',
      'eliminar_propiedades',
      'ver_clientes',
      'ver_pagos',
      'crear_contratos',
      'ver_reportes',
    ]],
    joined: 'Ene 2024',
  },
  {
    id: 'U-2',
    name: 'María López',
    email: 'maria@mobihouse.com',
    role: 'admin',
    status: 'active',
    permissions: [
      'ver_propiedades',
      'crear_propiedades',
      'editar_propiedades',
      'ver_clientes',
      'ver_pagos',
      'crear_contratos',
      'ver_reportes',
    ],
    joined: 'Mar 2024',
  },
  {
    id: 'U-3',
    name: 'Carlos Gómez',
    email: 'carlos.gomez@mobihouse.com',
    role: 'agente',
    status: 'active',
    permissions: [
      'ver_propiedades',
      'crear_propiedades',
      'editar_propiedades',
      'ver_clientes',
    ],
    joined: 'Jun 2024',
  },
  {
    id: 'U-4',
    name: 'Ana Contadora',
    email: 'ana@mobihouse.com',
    role: 'contador',
    status: 'active',
    permissions: ['ver_pagos', 'ver_reportes', 'ver_propiedades'],
    joined: 'Ago 2024',
  },
  {
    id: 'U-5',
    name: 'Lucía Recepción',
    email: 'lucia@mobihouse.com',
    role: 'recepcion',
    status: 'inactive',
    permissions: ['ver_clientes', 'ver_propiedades'],
    joined: 'Oct 2024',
  },
]

export const seedNotifications: AdminNotification[] = [
  {
    id: 'N-1',
    title: 'Nueva consulta',
    body: 'María Gómez preguntó por Loft Palermo',
    createdAt: daysAgo(0),
    read: false,
    type: 'consulta',
  },
  {
    id: 'N-2',
    title: 'Visita mañana 10:30',
    body: 'Juan Pérez — Dpto. Recoleta. Aún no confirmó.',
    createdAt: daysAgo(0),
    read: false,
    type: 'visita',
  },
  {
    id: 'N-3',
    title: 'Contrato por vencer',
    body: 'Alquiler Loft Palermo vence en 25 días',
    createdAt: daysAgo(1),
    read: false,
    type: 'contrato',
  },
  {
    id: 'N-4',
    title: 'Pago vencido',
    body: 'Laura Martínez — alquiler agosto pendiente',
    createdAt: daysAgo(2),
    read: true,
    type: 'pago',
  },
  {
    id: 'N-5',
    title: 'Reserva creada',
    body: 'Juan Pérez reservó Dpto. Recoleta por $5.000.000',
    createdAt: daysAgo(1),
    read: true,
    type: 'reserva',
  },
]

export const seedAudit: AuditEvent[] = [
  {
    id: 'A-1',
    actor: 'Mateo',
    action: 'inició sesión',
    target: 'Panel admin',
    createdAt: daysAgo(0),
  },
  {
    id: 'A-2',
    actor: 'Admin',
    action: 'modificó propiedad',
    target: '#P-1024 Dpto. Recoleta',
    createdAt: daysAgo(1),
  },
  {
    id: 'A-3',
    actor: 'Carlos Gómez',
    action: 'creó cliente',
    target: '#C-521 Juan Pérez',
    createdAt: daysAgo(25),
  },
  {
    id: 'A-4',
    actor: 'Carlos Gómez',
    action: 'cambió precio',
    target: '$120.000.000 → $115.000.000 (Casa Belgrano)',
    createdAt: daysAgo(5),
  },
  {
    id: 'A-5',
    actor: 'Andrés García',
    action: 'pausó publicación',
    target: 'PH Palermo Hollywood — WhatsApp',
    createdAt: daysAgo(7),
  },
]

export const seedActivity: ActivityItem[] = [
  {
    id: 'ACT-1',
    text: 'Nueva propiedad agregada — PH Palermo Hollywood',
    createdAt: daysAgo(0),
    type: 'propiedad',
  },
  {
    id: 'ACT-2',
    text: 'Nuevo cliente registrado — Sofía Fernández',
    createdAt: daysAgo(3),
    type: 'cliente',
  },
  {
    id: 'ACT-3',
    text: 'Visita agendada — Juan Pérez (mañana 10:30)',
    createdAt: daysAgo(1),
    type: 'visita',
  },
  {
    id: 'ACT-4',
    text: 'Propiedad reservada — Dpto. Recoleta',
    createdAt: daysAgo(1),
    type: 'reserva',
  },
  {
    id: 'ACT-5',
    text: 'Contrato creado — CT-1042',
    createdAt: daysAgo(1),
    type: 'contrato',
  },
  {
    id: 'ACT-6',
    text: 'Pago recibido — seña $5.000.000',
    createdAt: daysAgo(1),
    type: 'pago',
  },
]

export const seedPropertyMeta: Record<string, PropertyMeta> = {
  'seed-1': {
    propertyId: 'seed-1',
    code: 'P-1024',
    status: 'reservada',
    operation: 'venta',
    city: 'Córdoba',
    neighborhood: 'Nueva Córdoba',
    ownerName: 'Inmobiliaria MobiHouse',
    agentName: 'Carlos Gómez',
    publishedAt: daysAgo(30),
    updatedAt: daysAgo(1),
    expenses: '$85.000',
    taxes: '$12.000',
    commission: '3%',
    profitability: '4.2%',
    yearBuilt: 2018,
    history: [
      { date: '08/09', text: 'Precio actualizado' },
      { date: '07/09', text: 'Se agregó fotografía' },
      { date: '05/09', text: 'Estado cambiado a Reservada' },
    ],
    docs: [
      { name: 'Escritura', type: 'PDF' },
      { name: 'Plano', type: 'PDF' },
      { name: 'Reserva CT-1042', type: 'PDF' },
    ],
  },
  'seed-2': {
    propertyId: 'seed-2',
    code: 'P-1025',
    status: 'alquilada',
    operation: 'alquiler',
    city: 'CABA',
    neighborhood: 'Palermo',
    ownerName: 'Andrés García',
    agentName: 'Carlos Gómez',
    publishedAt: daysAgo(100),
    updatedAt: daysAgo(5),
    expenses: '$45.000',
    taxes: '$8.000',
    commission: '1 mes',
    profitability: '5.1%',
    yearBuilt: 2020,
    history: [
      { date: '01/09', text: 'Contrato de alquiler renovado' },
      { date: '15/08', text: 'Pago de alquiler registrado' },
    ],
    docs: [
      { name: 'Contrato alquiler', type: 'PDF' },
      { name: 'Inventario', type: 'PDF' },
    ],
  },
  'seed-3': {
    propertyId: 'seed-3',
    code: 'P-1026',
    status: 'disponible',
    operation: 'venta',
    city: 'CABA',
    neighborhood: 'Belgrano',
    ownerName: 'Laura Martínez',
    agentName: 'Carlos Gómez',
    publishedAt: daysAgo(45),
    updatedAt: daysAgo(5),
    expenses: '$120.000',
    taxes: '$25.000',
    commission: '3%',
    profitability: '3.8%',
    yearBuilt: 2015,
    history: [
      { date: '03/09', text: 'Precio ajustado a $115M' },
      { date: '20/08', text: 'Publicada en portales' },
    ],
    docs: [
      { name: 'Escritura', type: 'PDF' },
      { name: 'Reglamento', type: 'PDF' },
    ],
  },
  'seed-4': {
    propertyId: 'seed-4',
    code: 'P-1027',
    status: 'disponible',
    operation: 'venta',
    city: 'CABA',
    neighborhood: 'Palermo Hollywood',
    ownerName: 'Particular',
    agentName: 'Andrés García',
    publishedAt: daysAgo(12),
    updatedAt: daysAgo(2),
    expenses: '$55.000',
    taxes: '$9.500',
    commission: '3%',
    profitability: '4.0%',
    yearBuilt: 2012,
    history: [
      { date: '06/09', text: 'Nueva propiedad agregada' },
      { date: '06/09', text: 'Galería de fotos cargada' },
    ],
    docs: [{ name: 'Plano PH', type: 'PDF' }],
  },
}

export const seedCompany: CompanySettings = {
  name: 'MobiHouse Inmobiliaria',
  phone: '+54 351 555-1000',
  email: 'contacto@mobihouse.com',
  address: 'Av. Colón 1500, Córdoba',
  currency: 'ARS',
  dateFormat: 'DD/MM/YYYY',
  timezone: 'America/Argentina/Cordoba',
  language: 'es-AR',
}

export const adminSeed = {
  clients: seedClients,
  visits: seedVisits,
  sales: seedSales,
  rentals: seedRentals,
  contracts: seedContracts,
  payments: seedPayments,
  inquiries: seedInquiries,
  publications: seedPublications,
  documents: seedDocuments,
  users: seedUsers,
  notifications: seedNotifications,
  audit: seedAudit,
  activity: seedActivity,
  propertyMeta: seedPropertyMeta,
  company: seedCompany,
}
